// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umgawdvdogumfgjdvqqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtZ2F3ZHZkb2d1bWZnamR2cXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTUzNzAsImV4cCI6MjA3NDM5MTM3MH0.mssIfVu9eUvxuh3Ry-5T4TCc40Vm5fH8VDaLnEpexA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});